# Generated by Django 5.2 on 2025-11-26 09:07

import SessionApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(blank=True, editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$', 'Nom de salle invalide')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.CharField(max_length=500, validators=[SessionApp.models.validate_keywords]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
