# Generated by Django 5.2 on 2025-11-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0002_remove_session_created_at_remove_session_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(editable=False, max_length=12),
        ),
    ]
