# Generated by Django 5.2 on 2025-11-26 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizingcommittee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organizingcommittee',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='theme',
            field=models.CharField(choices=[('AI', 'Computer Science & AI'), ('ENG', 'Science & Engineering'), ('SOC', 'Social Sciences & Education'), ('INT', 'Interdisciplinary Themes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Le titre de la conférence doit contenir uniquement des lettres.', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='organizingcommittee',
            name='committee_role',
            field=models.CharField(choices=[('chair', 'Chair'), ('co-chair', 'Co-chair'), ('member', 'Member')], max_length=20),
        ),
    ]
